### ISSUE TITLE
Cant Name Items In Anvil

### ISSUE THREAD

**Issue by GitNuck** [coltonj96/UberEnchant#3]
When the anvil is enabled in the mechanics section of the yml file, you no longer can name items.

**Comment by coltonj96** [comment]
> When the anvil is enabled in the mechanics section of the yml file, you no longer can name items.

What version of UberEnchant are you using?

**Comment by GitNuck** [comment]
8.11.1

**Comment by coltonj96** [comment]
> 8.11.1

The latest version (8.11.2) fixes this issue.
https://dev.bukkit.org/projects/uberenchant/files/4930139
